### ISSUE TITLE
Synology applications for Mac

### ISSUE THREAD

**Issue by r53bertyboo** [ugurkocde/IntuneBrew#1]
Hi,

It would be great if IntuneBrew could provide Synology Active Backup for Business Client and Synology Drive Client applications, I have tried several times to get the Active Backup client to successfully install via the native Intune App tools but it always fails,

Thanks

**Comment by ugurkocde** [comment]
Hi @r53bertyboo ,

thanks for the request.

1. I was not able to find the "Synology Active Backup for Business Client" App in Homebrew which makes it hard for me to maintain. I can only add whats available in Homebrew.

2. You can now upload the Synology Drive Client with IntuneBrew.

This is how it will look like in Intune:

![grafik](https://github.com/user-attachments/assets/b35323c2-da40-485b-800e-dad5acc9f84a)
