### ISSUE TITLE
New app request

### ISSUE THREAD

**Issue by AndreaDelmonte** [ugurkocde/IntuneBrew#4]
Thanks again for your great job!
Could you also add FileZilla, Azure Storage Explorer, Figma, Git, Maven, Postman, SQL Server Management Studio, and Terraform?
Sorry, but our developers are picky!!! 😊

**Comment by ugurkocde** [comment]
Hi @AndreaDelmonte 

quick update: I have been able to add some of the apps you requested. Everything else will follow in one of the next updates.

Best
Ugur

**Comment by ugurkocde** [comment]
Added more than 50 apps now to IntuneBrew. More to follow :)
